### ISSUE TITLE
be careful, this dude store your tokens to get nitro gift. i just received unknown payment confirmation for nitro, request located in mumbai maharashta india

### ISSUE THREAD

**Issue by aaleexciting** [Mid0aria/owofarmbot#10]
![Screenshot (4768)](https://github.com/Mid0aria/owofarmbot/assets/75514317/32869c23-190a-4628-bd48-fdf623036f74)
![Screenshot (4770)](https://github.com/Mid0aria/owofarmbot/assets/75514317/ae020fe6-f758-4594-a72e-51211f3bc00e)
![IMG_4117](https://github.com/Mid0aria/owofarmbot/assets/75514317/eb61993e-e5f5-4356-bbcb-cf4b45b9e0c3)

**Comment by Mid0aria** [comment]
the project is fully open source so you can see the tokens are not repositories

**Comment by Mid0aria** [comment]
and i don't live in india

**Comment by Mid0aria** [comment]
![image](https://github.com/Mid0aria/owofarmbot/assets/45801669/1a1565c3-7344-4f25-8f9c-20e43d6b492e)
