### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by mallusrgreatv2** [Mid0aria/owofarmbot#101]
I think a discord server for this project would be pretty cool, people can ask for help, report bugs, or just chat

**Comment by boss6980** [comment]
> Sure, but I don't know how to use discord. If you want, I'll give you a perm and you can organize the server, is that okay ?

I'll manage your server give me permission

**Comment by mallusrgreatv2** [comment]
> Sure, but I don't know how to use discord. If you want, I'll give you a perm and you can organize the server, is that okay ?

Sure! my username is mallusrgreat, send the invite here and I'll join

**Comment by Mid0aria** [comment]
https://discord.gg/yd2BQ6Pz
