### ISSUE TITLE
Chat Ban Bypass

### ISSUE THREAD

**Issue by PixelGM** [Mid0aria/owofarmbot#103]
**Describe the bug**
It doesn't bypass ban in farming channel (channelid). Look at screenshot.

**To Reproduce**
Turn on owofarmbot and let AFK for around 2 hours

**Screenshots**
![Screenshot 2024-02-01 184121](https://github.com/Mid0aria/owofarmbot/assets/35326620/cd0d5ddc-408d-4a65-a3a6-b62526dd63a4)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: Latest (Feb 1, 2024)

**Comment by Mid0aria** [comment]
I'm out of town right now, I'll look into it when I get home.

**Comment by Mid0aria** [comment]
https://github.com/Mid0aria/owofarmbot/commit/91b121593a39ec523a4b1b2e1c56ff8e59e987b3 fixed
