### ISSUE TITLE
Extra Token bug

### ISSUE THREAD

**Issue by agcrisbp** [Mid0aria/owofarmbot#105]
**Describe the bug**
Even though extra tokens and gamble are set to 'false', they still run by itself.

**Screenshots**
![Cuplikan Layar_2024-02-08_06-58-49](https://github.com/Mid0aria/owofarmbot/assets/54905291/54b5fbad-09d5-449f-9fdc-79445309a263)

![Cuplikan Layar_2024-02-08_06-59-11](https://github.com/Mid0aria/owofarmbot/assets/54905291/2811d4fc-919c-4785-ba45-9928508aedef)

**Desktop:**
 - Ubuntu 23.10

---

**EDIT**
- Anything in config.json doesn't work.
![Cuplikan Layar_2024-02-08_07-09-00](https://github.com/Mid0aria/owofarmbot/assets/54905291/470d0a43-ca09-4be3-88e4-8a917644c3ea)
![Cuplikan Layar_2024-02-08_07-13-00](https://github.com/Mid0aria/owofarmbot/assets/54905291/4c5c0a64-f426-4d98-8ac5-431e767bf910)

**Comment by isobeast** [comment]
Same issue with me. for now i am using same TokenID in extra and kept all gambling to 1 with higher interval . This happened after there was update in bot . 

OS in use : MacOS

**Comment by crazyeee** [comment]
same issue on pc too
