### ISSUE TITLE
sometimes it just cant detect if theres a captcha

### ISSUE THREAD

**Issue by hoagggggggggggggggggggg** [Mid0aria/owofarmbot#107]
idk how it happened but i had it 4 times in a row on my alts 
![image](https://github.com/Mid0aria/owofarmbot/assets/144444943/6a2b4a04-c9d7-4ec8-8a1d-85a642ddf540)
![image1](https://github.com/Mid0aria/owofarmbot/assets/144444943/49636392-b985-4a2e-bde1-76c2ec48464c)

**Comment by Mid0aria** [comment]
When your internet is slow or the owo bot is running slowly, the farm bot cannot synchronise. therefore it cannot detect captcha messages
