### ISSUE TITLE
Error Message, then infinitely loading

### ISSUE THREAD

**Issue by Kayows12** [Mid0aria/owofarmbot#113]
This error message shows and then it keeps loading forever and doesn't work
![Screenshot_2024-05-04-15-29-40-14](https://github.com/Mid0aria/owofarmbot/assets/134359642/d24470d2-e062-454d-9276-f49741d4afff)

**Comment by Mid0aria** [comment]
Do not use Replit, if you do not have a computer, watch the termux video in readme.md
