### ISSUE TITLE
Termux Error

### ISSUE THREAD

**Issue by Kayows12** [Mid0aria/owofarmbot#119]
I'm using a new phone, it has android 13 in it. I tried upgrade or update using apt, it's giving errors. Same for git. It seems like new storage change in a13 is the cause. It says file inaccessible and the directory it shows seems to be different too than on the last phone.

**Comment by Mid0aria** [comment]
What's that got to do with me?

**Comment by Mid0aria** [comment]
you're going to ask the termux for help.

**Comment by NotRichit** [comment]
Do this 
```bash
termux-setup-storage
```
