### ISSUE TITLE
W cf h /w cf t play 

### ISSUE THREAD

**Issue by ahmet-bayrak** [Mid0aria/owofarmbot#123]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
When I play cf h cf t, I start with 10000 thousand owo. If I lose, it is twice that amount. If I lose again, it is 2 times that amount, so at the end I get 10000 thousand owo. 
![584E7918-7EFC-4A70-B9DA-82BDAB714D17](https://github.com/Mid0aria/owofarmbot/assets/172438593/bc2e5885-5d76-4486-a9c7-4a260fda029f)
![B25D5F46-2DA1-45CB-A7F4-056DA9A6C974](https://github.com/Mid0aria/owofarmbot/assets/172438593/bf8c8cde-ba49-4890-98db-3dcce1402faa)
![AA0B987B-FEA1-4B2E-B14E-F34DFE27FC9C](https://github.com/Mid0aria/owofarmbot/assets/172438593/c60c6903-061c-4e41-8b83-8f842d0eba1f)
![3B692B26-190D-4157-BDD9-787F1F16148B](https://github.com/Mid0aria/owofarmbot/assets/172438593/02099c40-5a23-4e2d-bee9-82e9391c1896)
![BDC74B0D-6D52-4476-903B-7EF4C1DF8923](https://github.com/Mid0aria/owofarmbot/assets/172438593/102d8637-5f84-4f82-8e93-48385779b3f3)
![788297AC-84CA-4AF8-BA05-C9AC61762FD3](https://github.com/Mid0aria/owofarmbot/assets/172438593/0694fa93-877d-45e9-9827-9410c7f139be)
![E20620BC-3B89-48E6-80C1-3258C2BC82FA](https://github.com/Mid0aria/owofarmbot/assets/172438593/d23af773-b1d7-44bc-911d-fab5c3a9d519)
![C268A940-C972-4F6A-8812-C67CE93E4D0A](https://github.com/Mid0aria/owofarmbot/assets/172438593/d20dadee-d436-4392-969a-eddb9e5904d8)

**Comment by Mid0aria** [comment]
?
