### ISSUE TITLE
I cant join your discord server

### ISSUE THREAD

**Issue by realphandat** [Mid0aria/owofarmbot#132]
my account is realphandat (1191703681637290086)

**Comment by Mid0aria** [comment]
![Uploading image.png…]()

**Comment by Mid0aria** [comment]
![image](https://github.com/user-attachments/assets/7b5a7bbd-1a52-4213-b958-43c3320d388e)

**Comment by realphandat** [comment]
![image](https://github.com/user-attachments/assets/c0c807fa-b006-4487-adba-963b3dffcb49)

**Comment by Mid0aria** [comment]
idc
