### ISSUE TITLE
Issue with phrases.json

### ISSUE THREAD

**Issue by VihaanReddyM** [Mid0aria/owofarmbot#17]
this did not happen to me, it happen to some other dude he sent me the image of the error.

![image](https://github.com/Mid0aria/owofarmbot/assets/87236325/26262750-86a6-4918-a21c-26465c94a4c9)

**Comment by VihaanReddyM** [comment]
pls tell me how to fix i will try to fix and learn js in the process thanks also can you give me your discord

**Comment by Mid0aria** [comment]
this guy didn't download phrases.json

**Comment by VihaanReddyM** [comment]
Yea but the updater needs to download it automatically right

**Comment by VihaanReddyM** [comment]
Yeah true but the old version of the updater needs to download the new version of the updater right
