### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by VihaanReddyM** [Mid0aria/owofarmbot#20]
It runned properly the first time but this time it is not working, the error is

```

                        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣤⣤⣶⣶⣶⣤⣤⣄⣀⡀
                        ⠀⠀⠀⠀⠀⢀⣤⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣄⠀⠀⠀⠀⠀⠀
                        ⠀⠀⠀⣠⣶⣿⣿⡿⣿⣿⣿⡿⠋⠉⠀⠀⠉⠙⢿⣿⣿⡿⣿⣿⣷⣦⡀⠀⠀⠀
                        ⠀⢀⣼⣿⣿⠟⠁⢠⣿⣿⠏⠀⠀⢠⣤⣤⡀⠀⠀⢻⣿⣿⡀⠙⢿⣿⣿⣦⠀⠀
                        ⣰⣿⣿⡟⠁i⠀⢸⣿⣿w⠀ ⢿⣿⣿⡟ a⠈⣿⣿⡇n⠀⠙⣿⣿⣷⡄
                        ⠈⠻⣿⣿⣦⣄⠀⠸⣿⣿⣆⠀t⠀⠉⠉⠀ ⠀⣸⣿⣿⠃⢀⣤⣾⣿⣿⠟⠁
                        ⠀⠀⠈⠻⣿⣿⣿⣶⣿⣿⣿⣦⣄⠀⠀u⢀⣠⣾⣿⣿⣿⣾⣿⣿⡿⠋⠁⠀⠀
                        ⠀⠀⠀⠀⠀⠙⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠁⠀⠀⠀⠀⠀
                        ⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠛⠛⠿⠿⠿⠿⠿⠿⠛⠋⠉⠀⠀⠀⠀⠀⠀


github.com/mid0aria
Made with love for e <3
OwO Farm Bot Started version 1.0.2.4
Captcha (ban) Bypass System by Aix version 0.1.6
opened socket client
node:events:489
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::1337
    at Server.setupListenHandle [as _listen2] (node:net:1829:16)
    at listenInCluster (node:net:1877:12)
    at Server.listen (node:net:1965:7)
    at Server.attach (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\node_modules\socket.io\dist\index.js:226:17)
    at new Server (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\node_modules\socket.io\dist\index.js:119:18)
    at module.exports (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\node_modules\socket.io\dist\index.js:809:33)
    at Object.<anonymous> (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\bot.js:77:38)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1856:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 1337
}

Node.js v20.3.0
```

idk what i did wrong, also what does socket.js do

**Comment by VihaanReddyM** [comment]
I was thinking organising all the files to make it look more nice. I will do it if your ok with that

**Comment by Mid0aria** [comment]
> It runned properly the first time but this time it is not working, the error is
> 
> ```
> 
>                         ⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣤⣤⣶⣶⣶⣤⣤⣄⣀⡀
>                         ⠀⠀⠀⠀⠀⢀⣤⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣄⠀⠀⠀⠀⠀⠀
>                         ⠀⠀⠀⣠⣶⣿⣿⡿⣿⣿⣿⡿⠋⠉⠀⠀⠉⠙⢿⣿⣿⡿⣿⣿⣷⣦⡀⠀⠀⠀
>                         ⠀⢀⣼⣿⣿⠟⠁⢠⣿⣿⠏⠀⠀⢠⣤⣤⡀⠀⠀⢻⣿⣿⡀⠙⢿⣿⣿⣦⠀⠀
>                         ⣰⣿⣿⡟⠁i⠀⢸⣿⣿w⠀ ⢿⣿⣿⡟ a⠈⣿⣿⡇n⠀⠙⣿⣿⣷⡄
>                         ⠈⠻⣿⣿⣦⣄⠀⠸⣿⣿⣆⠀t⠀⠉⠉⠀ ⠀⣸⣿⣿⠃⢀⣤⣾⣿⣿⠟⠁
>                         ⠀⠀⠈⠻⣿⣿⣿⣶⣿⣿⣿⣦⣄⠀⠀u⢀⣠⣾⣿⣿⣿⣾⣿⣿⡿⠋⠁⠀⠀
>                         ⠀⠀⠀⠀⠀⠙⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠛⠁⠀⠀⠀⠀⠀
>                         ⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠛⠛⠿⠿⠿⠿⠿⠿⠛⠋⠉⠀⠀⠀⠀⠀⠀
> 
> 
> github.com/mid0aria
> Made with love for e <3
> OwO Farm Bot Started version 1.0.2.4
> Captcha (ban) Bypass System by Aix version 0.1.6
> opened socket client
> node:events:489
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: listen EADDRINUSE: address already in use :::1337
>     at Server.setupListenHandle [as _listen2] (node:net:1829:16)
>     at listenInCluster (node:net:1877:12)
>     at Server.listen (node:net:1965:7)
>     at Server.attach (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\node_modules\socket.io\dist\index.js:226:17)
>     at new Server (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\node_modules\socket.io\dist\index.js:119:18)
>     at module.exports (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\node_modules\socket.io\dist\index.js:809:33)
>     at Object.<anonymous> (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\bot.js:77:38)
>     at Module._compile (node:internal/modules/cjs/loader:1255:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
>     at Module.load (node:internal/modules/cjs/loader:1113:32)
> Emitted 'error' event on Server instance at:
>     at emitErrorNT (node:net:1856:8)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
>   code: 'EADDRINUSE',
>   errno: -4091,
>   syscall: 'listen',
>   address: '::',
>   port: 1337
> }
> 
> Node.js v20.3.0
> ```
> 
> idk what i did wrong, also what does socket.js do

There may be another application using the 1337 port or the terminal (cmd) may be left open, so it may be giving a port error.

**Comment by Mid0aria** [comment]
> I was thinking organising all the files to make it look more nice. I will do it if your ok with that

im ok

**Comment by VihaanReddyM** [comment]
ok

**Comment by VihaanReddyM** [comment]
what is the blank.js file for
