### ISSUE TITLE
Write the features you want to be added under this heading.

### ISSUE THREAD

**Issue by Mid0aria** [Mid0aria/owofarmbot#24]
.

**Comment by VihaanReddyM** [comment]
I was working on special gems, here is the code 

```
function getinv(token, channelid, tokentype, gemc, collectc) {
    request.post(
        {
            headers: {
                authorization: token,
            },
            url:
                "https://discord.com/api/v9/channels/" +
                channelid +
                "/messages",
            json: {
                content: "owo inv",
                nonce: nonce(),
                tts: false,
                flags: 0,
            },
        },
        function (error, response, body) {}
    ); //coded by @mid0aria on github
    setTimeout(() => {
        request.get(
            {
                headers: {
                    authorization: token,
                },
                url:
                    "https://discord.com/api/v9/channels/" +
                    channelid +
                    "/messages?limit=1",
            },
            function (error, response, body) {
                var bod = JSON.parse(body);
                var cont = bod[0].content;
                console.log(cont);
                if (gemc == "gemvar") {
                    var empgem = "";
                    var luckgem = "";
                    var huntgem = "";
                    var specialgem = "";
                    if (collectc.contains("huntgem")) {
                        switch (true) {
                            case cont.includes("`057`"):
                                huntgem = "57";
                                break;
                            case cont.includes("`056`"):
                                huntgem = "56";
                                break;
                            case cont.includes("`055`"):
                                huntgem = "55";
                                break;
                            case cont.includes("`054`"):
                                huntgem = "54";
                                break;
                            case cont.includes("`053`"):
                                huntgem = "53";
                                break;
                            case cont.includes("`052`"):
                                huntgem = "52";
                                break;
                            case cont.includes("`051`"):
                                huntgem = "51";
                                break;
                            default:
                                break;
                        }
                    }
                    if (collectc.contains("empgem")) {
                        switch (true) {
                            case cont.includes("`071`"):
                                empgem = "71";
                                break;
                            case cont.includes("`070`"):
                                empgem = "70";
                                break;
                            case cont.includes("`069`"):
                                empgem = "69";
                                break;
                            case cont.includes("`068`"):
                                empgem = "68";
                                break;
                            case cont.includes("`067`"):
                                empgem = "67";
                                break;
                            case cont.includes("`066`"):
                                empgem = "66";
                                break;
                            case cont.includes("`065`"):
                                empgem = "65";
                                break;
                            default:
                                break;
                        }
                    }
                    if (collectc.contains("luckgem")) {
                        switch (true) {
                            case cont.includes("`078`"):
                                luckgem = "78";
                                break;
                            case cont.includes("`077`"):
                                luckgem = "77";
                                break;
                            case cont.includes("`076`"):
                                luckgem = "76";
                                break;
                            case cont.includes("`075`"):
                                luckgem = "75";
                                break;
                            case cont.includes("`074`"):
                                luckgem = "74";
                                break;
                            case cont.includes("`073`"):
                                luckgem = "73";
                                break;
                            case cont.includes("`072`"):
                                luckgem = "72";
                                break;
                            default:
                                break;
                        }
                    }
                    if (collectc.contains("specialgem")) {
                        switch (true) {
                            case cont.include("`085`"):
                                specialgem = "85";
                                break;
                            case cont.include("`084`"):
                                specialgem = "84";
                                break;
                            case cont.include("`083`"):
                                specialgem = "83";
                                break;
                            case cont.include("`082`"):
                                specialgem = "82";
                                break;
                            case cont.include("`081`"):
                                specialgem = "81";
                                break;
                            case cont.include("`080`"):
                                specialgem = "80";
                                break;
                            case cont.include("``079"):
                                specialgem = "79";
                                break;
                            default:
                                break;                    
                        }
                    }

                    if (huntgem == "" && empgem == "" && luckgem == "") {
                        return 0;
                    } else {
                        if (
                            collectc.contains("huntgem") &&
                            collectc.contains("empgem") &&
                            collectc.contains("luckgem")
                        ) {
                            var gem = huntgem + " " + empgem + " " + luckgem;
                        } else if (
                            collectc.contains("huntgem") == false &&
                            collectc.contains("empgem") == true &&
                            collectc.contains("luckgem") == true
                        ) {
                            var gem = empgem + " " + luckgem ;
                        } else if (
                            collectc.contains("huntgem") == true &&
                            collectc.contains("empgem") == false && 
                            collectc.contains("luckgem") == true
                        ) {
                            var gem = huntgem + " " + luckgem;
                        } else if (
                            collectc.contains("huntgem") == true &&
                            collectc.contains("empgem") == true &&
                            collectc.contains("luckgem") == false
                        ) {
                            var gem = huntgem + " " + empgem;
                        } else if (
                            collectc.contains("huntgem") == true &&
                            collectc.contains("empgem") == false &&
                            collectc.contains("luckgem") == false
                        ) {
                            var gem = huntgem;
                        } else if (
                            collectc.contains("huntgem") == false &&
                            collectc.contains("empgem") == true &&
                            collectc.contains("luckgem") == false
                        ) {
                            var gem = empgem;
                        } else if (
                            collectc.contains("huntgem") == false &&
                            collectc.contains("empgem") == false &&
                            collectc.contains("luckgem") == true
                        ) {
                            var gem = luckgem;
                        }
                        gemuse(token, gem, channelid, tokentype);
                    }
                }

                if (settings.inventory.lootboxcheck == "true") {
                    if (cont.includes("`050`")) {
                        setTimeout(() => {
                            boxuse(token, "lootbox all", channelid, tokentype);
                        }, 2000);
                    }
                }

                if (settings.inventory.fabledlootboxcheck == "true") {
                    if (cont.includes("`049`")) {
                        setTimeout(() => {
                            boxuse(
                                token,
                                "lootbox fabled all",
                                channelid,
                                tokentype
                            );
                        }, 2000);
                    }
                }

                if (settings.inventory.cratecheck == "true") {
                    if (cont.includes("`100`")) {
                        setTimeout(() => {
                            boxuse(token, "crate all", channelid, tokentype);
                        }, 2000);
                    }
                }
                if (settings.inventory.eventcheck == "true") {
                    if (cont.includes("`018`")) {
                        // valentines day
                        setTimeout(() => {
                            eventuse(token, "18", channelid, tokentype);
                        }, 2000); //E <3
                    }
                    if (cont.includes("`019`")) {
                        // anniversary day
                        setTimeout(() => {
                            eventuse(token, "19", channelid, tokentype);
                        }, 2000);
                    }
                    if (cont.includes("`020`")) {
                        // fakelootbox
                        setTimeout(() => {
                            eventuse(token, "20", channelid, tokentype);
                        }, 2000);
                    }
                }
            }
        );
    }, 3000);
}
```
i dont know the logic you did not make the changes

**Comment by VihaanReddyM** [comment]
- [ ] added variable special
- [ ] check if it is there or not

**Comment by Mid0aria** [comment]
whats special gems

**Comment by Mid0aria** [comment]
I added

**Comment by Mid0aria** [comment]
> I was working on special gems, here is the code
> 
> ```
> function getinv(token, channelid, tokentype, gemc, collectc) {
>     request.post(
>         {
>             headers: {
>                 authorization: token,
>             },
>             url:
>                 "https://discord.com/api/v9/channels/" +
>                 channelid +
>                 "/messages",
>             json: {
>                 content: "owo inv",
>                 nonce: nonce(),
>                 tts: false,
>                 flags: 0,
>             },
>         },
>         function (error, response, body) {}
>     ); //coded by @mid0aria on github
>     setTimeout(() => {
>         request.get(
>             {
>                 headers: {
>                     authorization: token,
>                 },
>                 url:
>                     "https://discord.com/api/v9/channels/" +
>                     channelid +
>                     "/messages?limit=1",
>             },
>             function (error, response, body) {
>                 var bod = JSON.parse(body);
>                 var cont = bod[0].content;
>                 console.log(cont);
>                 if (gemc == "gemvar") {
>                     var empgem = "";
>                     var luckgem = "";
>                     var huntgem = "";
>                     var specialgem = "";
>                     if (collectc.contains("huntgem")) {
>                         switch (true) {
>                             case cont.includes("`057`"):
>                                 huntgem = "57";
>                                 break;
>                             case cont.includes("`056`"):
>                                 huntgem = "56";
>                                 break;
>                             case cont.includes("`055`"):
>                                 huntgem = "55";
>                                 break;
>                             case cont.includes("`054`"):
>                                 huntgem = "54";
>                                 break;
>                             case cont.includes("`053`"):
>                                 huntgem = "53";
>                                 break;
>                             case cont.includes("`052`"):
>                                 huntgem = "52";
>                                 break;
>                             case cont.includes("`051`"):
>                                 huntgem = "51";
>                                 break;
>                             default:
>                                 break;
>                         }
>                     }
>                     if (collectc.contains("empgem")) {
>                         switch (true) {
>                             case cont.includes("`071`"):
>                                 empgem = "71";
>                                 break;
>                             case cont.includes("`070`"):
>                                 empgem = "70";
>                                 break;
>                             case cont.includes("`069`"):
>                                 empgem = "69";
>                                 break;
>                             case cont.includes("`068`"):
>                                 empgem = "68";
>                                 break;
>                             case cont.includes("`067`"):
>                                 empgem = "67";
>                                 break;
>                             case cont.includes("`066`"):
>                                 empgem = "66";
>                                 break;
>                             case cont.includes("`065`"):
>                                 empgem = "65";
>                                 break;
>                             default:
>                                 break;
>                         }
>                     }
>                     if (collectc.contains("luckgem")) {
>                         switch (true) {
>                             case cont.includes("`078`"):
>                                 luckgem = "78";
>                                 break;
>                             case cont.includes("`077`"):
>                                 luckgem = "77";
>                                 break;
>                             case cont.includes("`076`"):
>                                 luckgem = "76";
>                                 break;
>                             case cont.includes("`075`"):
>                                 luckgem = "75";
>                                 break;
>                             case cont.includes("`074`"):
>                                 luckgem = "74";
>                                 break;
>                             case cont.includes("`073`"):
>                                 luckgem = "73";
>                                 break;
>                             case cont.includes("`072`"):
>                                 luckgem = "72";
>                                 break;
>                             default:
>                                 break;
>                         }
>                     }
>                     if (collectc.contains("specialgem")) {
>                         switch (true) {
>                             case cont.include("`085`"):
>                                 specialgem = "85";
>                                 break;
>                             case cont.include("`084`"):
>                                 specialgem = "84";
>                                 break;
>                             case cont.include("`083`"):
>                                 specialgem = "83";
>                                 break;
>                             case cont.include("`082`"):
>                                 specialgem = "82";
>                                 break;
>                             case cont.include("`081`"):
>                                 specialgem = "81";
>                                 break;
>                             case cont.include("`080`"):
>                                 specialgem = "80";
>                                 break;
>                             case cont.include("``079"):
>                                 specialgem = "79";
>                                 break;
>                             default:
>                                 break;                    
>                         }
>                     }
> 
>                     if (huntgem == "" && empgem == "" && luckgem == "") {
>                         return 0;
>                     } else {
>                         if (
>                             collectc.contains("huntgem") &&
>                             collectc.contains("empgem") &&
>                             collectc.contains("luckgem")
>                         ) {
>                             var gem = huntgem + " " + empgem + " " + luckgem;
>                         } else if (
>                             collectc.contains("huntgem") == false &&
>                             collectc.contains("empgem") == true &&
>                             collectc.contains("luckgem") == true
>                         ) {
>                             var gem = empgem + " " + luckgem ;
>                         } else if (
>                             collectc.contains("huntgem") == true &&
>                             collectc.contains("empgem") == false && 
>                             collectc.contains("luckgem") == true
>                         ) {
>                             var gem = huntgem + " " + luckgem;
>                         } else if (
>                             collectc.contains("huntgem") == true &&
>                             collectc.contains("empgem") == true &&
>                             collectc.contains("luckgem") == false
>                         ) {
>                             var gem = huntgem + " " + empgem;
>                         } else if (
>                             collectc.contains("huntgem") == true &&
>                             collectc.contains("empgem") == false &&
>                             collectc.contains("luckgem") == false
>                         ) {
>                             var gem = huntgem;
>                         } else if (
>                             collectc.contains("huntgem") == false &&
>                             collectc.contains("empgem") == true &&
>                             collectc.contains("luckgem") == false
>                         ) {
>                             var gem = empgem;
>                         } else if (
>                             collectc.contains("huntgem") == false &&
>                             collectc.contains("empgem") == false &&
>                             collectc.contains("luckgem") == true
>                         ) {
>                             var gem = luckgem;
>                         }
>                         gemuse(token, gem, channelid, tokentype);
>                     }
>                 }
> 
>                 if (settings.inventory.lootboxcheck == "true") {
>                     if (cont.includes("`050`")) {
>                         setTimeout(() => {
>                             boxuse(token, "lootbox all", channelid, tokentype);
>                         }, 2000);
>                     }
>                 }
> 
>                 if (settings.inventory.fabledlootboxcheck == "true") {
>                     if (cont.includes("`049`")) {
>                         setTimeout(() => {
>                             boxuse(
>                                 token,
>                                 "lootbox fabled all",
>                                 channelid,
>                                 tokentype
>                             );
>                         }, 2000);
>                     }
>                 }
> 
>                 if (settings.inventory.cratecheck == "true") {
>                     if (cont.includes("`100`")) {
>                         setTimeout(() => {
>                             boxuse(token, "crate all", channelid, tokentype);
>                         }, 2000);
>                     }
>                 }
>                 if (settings.inventory.eventcheck == "true") {
>                     if (cont.includes("`018`")) {
>                         // valentines day
>                         setTimeout(() => {
>                             eventuse(token, "18", channelid, tokentype);
>                         }, 2000); //E <3
>                     }
>                     if (cont.includes("`019`")) {
>                         // anniversary day
>                         setTimeout(() => {
>                             eventuse(token, "19", channelid, tokentype);
>                         }, 2000);
>                     }
>                     if (cont.includes("`020`")) {
>                         // fakelootbox
>                         setTimeout(() => {
>                             eventuse(token, "20", channelid, tokentype);
>                         }, 2000);
>                     }
>                 }
>             }
>         );
>     }, 3000);
> }
> ```
> 
> i dont know the logic you did not make the changes

I added

**Comment by VihaanReddyM** [comment]
ok

**Comment by VihaanReddyM** [comment]
i had this idea where the bot will sac all the animals till the epic tear and sell the animals from the other tear, i just don`t know how to execute it

**Comment by VihaanReddyM** [comment]
A captcha solver maybe

**Comment by VihaanReddyM** [comment]
also add 22 the beehives

**Comment by VihaanReddyM** [comment]
you there

**Comment by VihaanReddyM** [comment]
I made this pls see

<details>
The code
function animals(token, tokentype, channelid, type) {

    switch (true) {
        case type == "sacrifice":
            var animalcheck = true;
            break;
        case type == "sell":
            var animalcheck = true;
            break;
        default:
            var animalcheck = false;
            break;
    }    
    if (type == "sacrifice") {
        var sac = " common uncommon rare epic"
    }

    if (animalcheck) {
        request.post(
            {
                headers: {
                    authorization: token,
                },
                url:
                    "https://discord.com/api/v9/channels/" +
                    channelid +
                    "/messages",
                json: {
                    content: "owo " + type + sac,
                    nonce: nonce(),
                    tts: false,
                    flags: 0,
                },
            },
            function (error, response, body) {
                console.log(
                    chalk.red(
                        `${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}`
                    ) +
                        chalk.magenta(" [" + tokentype + "]") +
                        chalk.yellow(" Animals ✅ / Type: " + type)
                );
            }
        );
    } else {
        console.log(
            chalk.red(
                `${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}`
            ) +
                chalk.magenta(" [" + tokentype + "]") +
                chalk.yellow(" Animals ❌ / Error: Incorrect Type")
        );
    }
}

</details>

**Comment by Mid0aria** [comment]
> I made this pls see

added

**Comment by VihaanReddyM** [comment]
Thanks

**Comment by VihaanReddyM** [comment]
Hey i have new feature, whenever we update the config.json the credentials gets reset so we can make it so that they won't

**Comment by VihaanReddyM** [comment]
i had given a few ideas can you look in to it 
pls

**Comment by VihaanReddyM** [comment]
@Mid0aria add checklist plsss

**Comment by Mid0aria** [comment]
> @Mid0aria add checklist plsss

show example

**Comment by Mid0aria** [comment]
> @Mid0aria add checklist plsss

show example

**Comment by VihaanReddyM** [comment]
like our bot will send "owo cl", then it will collect and see what is done, 
we can see the list is completed or not in the list we need to get 3 lb and wc. we need to complete our vote, and send a cookie. it is like quest only and gives a lb and wc and 1000 in cash

lb = lootbpx
wc= weapon create

**Comment by Mid0aria** [comment]
I do not understand what you wanted to say

**Comment by Mid0aria** [comment]
@VihaanReddyM i need to make a model for captcha solver i need lots of owo captcha pictures can you help me

**Comment by VihaanReddyM** [comment]
yea i can i thnk i will start a python script and automate it is that ok
i will invite you to the repo

**Comment by VihaanReddyM** [comment]
@Mid0aria ok

**Comment by VihaanReddyM** [comment]
i have sent a invitation for you to collab with me in the repo

**Comment by Kayows12** [comment]
support for replit? then it can run on other devices like android or ios too

**Comment by VihaanReddyM** [comment]
like our bot will send "owo cl", then it will collect and see what is done,
we can see the list is completed or not in the list we need to get 3 lb and wc. we need to complete our vote, and send a cookie. it is like quest only and gives a lb and wc and 1000 in cash

lb = lootbpx
wc= weapon create

**Comment by Mid0aria** [comment]
> like our bot will send "owo cl",...

added

**Comment by rulzzistanz** [comment]
i got banned from owo because the captcha i didnt get any notification from my computer. idk its sometimes comes. how i can fix?

**Comment by Mid0aria** [comment]
> i got banned from owo because the captcha i didnt get any notification from my computer. idk its sometimes comes. how i can fix?

![image](https://github.com/Mid0aria/owofarmbot/assets/45801669/92c0c519-1452-4399-8709-087425e5205c)
👍

**Comment by VihaanReddyM** [comment]
- [ ] Make it automatically send "owo cookie @<Alt>" automatically when starts
- [ ] Make it so that out credentials dont disappear from the json file when a change is made to the config file in repo

**Comment by VihaanReddyM** [comment]
> > I was working on special gems, here is the code
> > ```
> > function getinv(token, channelid, tokentype, gemc, collectc) {
> >     request.post(
> >         {
> >             headers: {
> >                 authorization: token,
> >             },
> >             url:
> >                 "https://discord.com/api/v9/channels/" +
> >                 channelid +
> >                 "/messages",
> >             json: {
> >                 content: "owo inv",
> >                 nonce: nonce(),
> >                 tts: false,
> >                 flags: 0,
> >             },
> >         },
> >         function (error, response, body) {}
> >     ); //coded by @mid0aria on github
> >     setTimeout(() => {
> >         request.get(
> >             {
> >                 headers: {
> >                     authorization: token,
> >                 },
> >                 url:
> >                     "https://discord.com/api/v9/channels/" +
> >                     channelid +
> >                     "/messages?limit=1",
> >             },
> >             function (error, response, body) {
> >                 var bod = JSON.parse(body);
> >                 var cont = bod[0].content;
> >                 console.log(cont);
> >                 if (gemc == "gemvar") {
> >                     var empgem = "";
> >                     var luckgem = "";
> >                     var huntgem = "";
> >                     var specialgem = "";
> >                     if (collectc.contains("huntgem")) {
> >                         switch (true) {
> >                             case cont.includes("`057`"):
> >                                 huntgem = "57";
> >                                 break;
> >                             case cont.includes("`056`"):
> >                                 huntgem = "56";
> >                                 break;
> >                             case cont.includes("`055`"):
> >                                 huntgem = "55";
> >                                 break;
> >                             case cont.includes("`054`"):
> >                                 huntgem = "54";
> >                                 break;
> >                             case cont.includes("`053`"):
> >                                 huntgem = "53";
> >                                 break;
> >                             case cont.includes("`052`"):
> >                                 huntgem = "52";
> >                                 break;
> >                             case cont.includes("`051`"):
> >                                 huntgem = "51";
> >                                 break;
> >                             default:
> >                                 break;
> >                         }
> >                     }
> >                     if (collectc.contains("empgem")) {
> >                         switch (true) {
> >                             case cont.includes("`071`"):
> >                                 empgem = "71";
> >                                 break;
> >                             case cont.includes("`070`"):
> >                                 empgem = "70";
> >                                 break;
> >                             case cont.includes("`069`"):
> >                                 empgem = "69";
> >                                 break;
> >                             case cont.includes("`068`"):
> >                                 empgem = "68";
> >                                 break;
> >                             case cont.includes("`067`"):
> >                                 empgem = "67";
> >                                 break;
> >                             case cont.includes("`066`"):
> >                                 empgem = "66";
> >                                 break;
> >                             case cont.includes("`065`"):
> >                                 empgem = "65";
> >                                 break;
> >                             default:
> >                                 break;
> >                         }
> >                     }
> >                     if (collectc.contains("luckgem")) {
> >                         switch (true) {
> >                             case cont.includes("`078`"):
> >                                 luckgem = "78";
> >                                 break;
> >                             case cont.includes("`077`"):
> >                                 luckgem = "77";
> >                                 break;
> >                             case cont.includes("`076`"):
> >                                 luckgem = "76";
> >                                 break;
> >                             case cont.includes("`075`"):
> >                                 luckgem = "75";
> >                                 break;
> >                             case cont.includes("`074`"):
> >                                 luckgem = "74";
> >                                 break;
> >                             case cont.includes("`073`"):
> >                                 luckgem = "73";
> >                                 break;
> >                             case cont.includes("`072`"):
> >                                 luckgem = "72";
> >                                 break;
> >                             default:
> >                                 break;
> >                         }
> >                     }
> >                     if (collectc.contains("specialgem")) {
> >                         switch (true) {
> >                             case cont.include("`085`"):
> >                                 specialgem = "85";
> >                                 break;
> >                             case cont.include("`084`"):
> >                                 specialgem = "84";
> >                                 break;
> >                             case cont.include("`083`"):
> >                                 specialgem = "83";
> >                                 break;
> >                             case cont.include("`082`"):
> >                                 specialgem = "82";
> >                                 break;
> >                             case cont.include("`081`"):
> >                                 specialgem = "81";
> >                                 break;
> >                             case cont.include("`080`"):
> >                                 specialgem = "80";
> >                                 break;
> >                             case cont.include("``079"):
> >                                 specialgem = "79";
> >                                 break;
> >                             default:
> >                                 break;                    
> >                         }
> >                     }
> > 
> >                     if (huntgem == "" && empgem == "" && luckgem == "") {
> >                         return 0;
> >                     } else {
> >                         if (
> >                             collectc.contains("huntgem") &&
> >                             collectc.contains("empgem") &&
> >                             collectc.contains("luckgem")
> >                         ) {
> >                             var gem = huntgem + " " + empgem + " " + luckgem;
> >                         } else if (
> >                             collectc.contains("huntgem") == false &&
> >                             collectc.contains("empgem") == true &&
> >                             collectc.contains("luckgem") == true
> >                         ) {
> >                             var gem = empgem + " " + luckgem ;
> >                         } else if (
> >                             collectc.contains("huntgem") == true &&
> >                             collectc.contains("empgem") == false && 
> >                             collectc.contains("luckgem") == true
> >                         ) {
> >                             var gem = huntgem + " " + luckgem;
> >                         } else if (
> >                             collectc.contains("huntgem") == true &&
> >                             collectc.contains("empgem") == true &&
> >                             collectc.contains("luckgem") == false
> >                         ) {
> >                             var gem = huntgem + " " + empgem;
> >                         } else if (
> >                             collectc.contains("huntgem") == true &&
> >                             collectc.contains("empgem") == false &&
> >                             collectc.contains("luckgem") == false
> >                         ) {
> >                             var gem = huntgem;
> >                         } else if (
> >                             collectc.contains("huntgem") == false &&
> >                             collectc.contains("empgem") == true &&
> >                             collectc.contains("luckgem") == false
> >                         ) {
> >                             var gem = empgem;
> >                         } else if (
> >                             collectc.contains("huntgem") == false &&
> >                             collectc.contains("empgem") == false &&
> >                             collectc.contains("luckgem") == true
> >                         ) {
> >                             var gem = luckgem;
> >                         }
> >                         gemuse(token, gem, channelid, tokentype);
> >                     }
> >                 }
> > 
> >                 if (settings.inventory.lootboxcheck == "true") {
> >                     if (cont.includes("`050`")) {
> >                         setTimeout(() => {
> >                             boxuse(token, "lootbox all", channelid, tokentype);
> >                         }, 2000);
> >                     }
> >                 }
> > 
> >                 if (settings.inventory.fabledlootboxcheck == "true") {
> >                     if (cont.includes("`049`")) {
> >                         setTimeout(() => {
> >                             boxuse(
> >                                 token,
> >                                 "lootbox fabled all",
> >                                 channelid,
> >                                 tokentype
> >                             );
> >                         }, 2000);
> >                     }
> >                 }
> > 
> >                 if (settings.inventory.cratecheck == "true") {
> >                     if (cont.includes("`100`")) {
> >                         setTimeout(() => {
> >                             boxuse(token, "crate all", channelid, tokentype);
> >                         }, 2000);
> >                     }
> >                 }
> >                 if (settings.inventory.eventcheck == "true") {
> >                     if (cont.includes("`018`")) {
> >                         // valentines day
> >                         setTimeout(() => {
> >                             eventuse(token, "18", channelid, tokentype);
> >                         }, 2000); //E <3
> >                     }
> >                     if (cont.includes("`019`")) {
> >                         // anniversary day
> >                         setTimeout(() => {
> >                             eventuse(token, "19", channelid, tokentype);
> >                         }, 2000);
> >                     }
> >                     if (cont.includes("`020`")) {
> >                         // fakelootbox
> >                         setTimeout(() => {
> >                             eventuse(token, "20", channelid, tokentype);
> >                         }, 2000);
> >                     }
> >                 }
> >             }
> >         );
> >     }, 3000);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i dont know the logic you did not make the changes
> 
> I added

Also pls delete this missive message

**Comment by Kayows12** [comment]
auto captcha solver, auto huntbot?

**Comment by Q21042007** [comment]
how can i use the gem i wanted

**Comment by thevzz** [comment]
@Mid0aria @VihaanReddyM can you add a feature which would multiply ( * 2) startbet value if bet is lost?
example;
owo coinflip 2
lost bet
owo coinflip 4
lost bet
owo coinflip 8
won bet

and then it returns to the startbet

**Comment by peng1285** [comment]
can you add auto gamble coinflip like this
if i flip 10000 and win it will repeat and if i lose it will Continue to flip 40000 if i win bot will go back to flip 10000 if i lose it will continue to flip 90000 if i win bot will go back to flip 10000 if i lose it will continue to flip 150000 and go back to 10000

**Comment by peng1285** [comment]
> @Mid0aria @VihaanReddyM can you add a feature which would multiply ( * 2) startbet value if bet is lost? example; owo coinflip 2 lost bet owo coinflip 4 lost bet owo coinflip 8 won bet
> 
> and then it returns to the startbet

like this and we can change amount -,-

**Comment by VihaanReddyM** [comment]
it is done i opened a PR also pls check

**Comment by yvreK** [comment]
Please make it so that it just pauses the bot for a second and after it detects the "I have verified that you are a human" message from owo bot it continues.. That way we don't have to restart the bot again and again.. Thankyou 😅

**Comment by DatdatItSn02** [comment]
buy ring 

if (settings.buyring == "true") {
    var rpcbuyring = "✅";
} else {
    var rpcbuyring = "❌";
}

setTimeout(() => {
    socketio.emit("bot", {
        info: `Hunt and Battle: ${rpchab} BanBypass: ${rpcbanb} Inventory Check: ${rpcinventory} Animals: ${rpcanimals} Buy Ring: ${rpcbuyring}`,
    });
}, 2500);

rpc.on("ready", () => {
    console.log(chalk.blue("Discord RPC Started!"));

    rpc.setActivity({
        details: rpcdetails,
        state: `Hunt and Battle: ${rpchab} BanBypass: ${rpcbanb} Inventory: ${rpcinventory} Animals: ${rpcanimals} Buy Ring: ${rpcbuyring}`,
        startTimestamp: new Date(),
        largeImageKey: "owo",
        largeImageText: "v" + version,
        smallImageKey: "ban",
        smallImageText: rpcbant,
        instance: false,
        buttons: [
            {
                label: "Farm Bot",
                url: "https://github.com/Mid0aria/owofarmbot",
            },
            {
                label: "Github",
                url: "https://github.com/Mid0aria/",
            },
        ],
    });
});

//--------------------------------BUY RING-------------------------------------------------//
if (settings.buyring == "true") {
    setInterval(() => {
        buyring(maintoken, "Main Token", mainchannelid);
        if (global.etoken) {
            buyring(extratoken, "Extra Token", extrachannelid);
        }
    }, 15000);
}

/**
 * Sends a buy common ring message to a Discord channel using the provided token and channel ID.
 * @param {string} token - The Discord bot token.
 * @param {string} tokentype - The type of token being used.
 * @param {string} channelid - The ID of the Discord channel to send the message to.
 */
function buyring(token, tokentype, channelid) {

    var ct = "owo buy 1";

    request.post(
        {
            headers: {
                authorization: token,
            },
            url:
                "https://discord.com/api/v9/channels/" +
                channelid +
                "/messages",
            json: {
                content: ct,
                nonce: nonce(),
                tts: false,
                flags: 0,
            },
        },
        function (error, response, body) {
            console.log(
                chalk.red(
                    `${new Date().getHours()}:${new Date().getMinutes()}:${new Date().getSeconds()}`
                ) +
                    chalk.magenta(" [" + tokentype + "]") +
                    chalk.yellow(" Buy Ring ✅")
            );
        }
    );
}

**Comment by ixmxk** [comment]
/ > Captcha Bypass
(node:27584) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created

**Comment by VihaanReddyM** [comment]
pls make a issue and then send a screenshot and then maybe we can solve it

**Comment by Kayows12** [comment]
• Option to set intervals between messages
• Pause for X time, if there's an captcha in dms or chat
• Customisable RPC

**Comment by CelliniaYuu** [comment]
is this a bug? (bot.js file line 1585 vs code)
function extrabancheck(token, channelid) {
    request.get(
        {
            headers: {
                **authorization: token,**
            },
            url:
                "https://discord.com/api/v9/channels/" +
                channelid +
                "/messages?limit=1",
        },
here, bancheck for etoken, but in bot.js file i checked was use **authorization: token,**
p/s: i got banned 12h in etoken :')))

**Comment by yvreK** [comment]
> Please make it so that it just pauses the bot for a second and after it detects the "I have verified that you are a human" message from owo bot it continues.. That way we don't have to restart the bot again and again.. Thankyou 😅

Just gonna up my recom:3

**Comment by Kayows12** [comment]
- Option to pause bot if a captcha message comes up.
- Option to run the bot for only a selected amount of time. (I noticed that the owo captcha was recieved after 40min of continuous running in first try) So, maybe also custom running times like running for x times then stop for x, and loop.

**Comment by Mid0aria** [comment]
> - Option to pause bot if a captcha message comes up.
> - Option to run the bot for only a selected amount of time. (I noticed that the owo captcha was recieved after 40min of continuous running in first try) So, maybe also custom running times like running for x times then stop for x, and loop.

I will consider adding it to v2

**Comment by Kayows12** [comment]
Can you use some code from https://github.com/LongAKolangle/discord-owo-selfbot/ ? It has some great features and timings on it are perfect along with alternative captcha solving methods. Paired with this selfbot, It would be crazy good.
