### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'description')

### ISSUE THREAD

**Issue by VOREGA** [Mid0aria/owofarmbot#27]
![Ekran Alıntısı](https://github.com/Mid0aria/owofarmbot/assets/72041595/f811aa9e-e265-405e-a5f7-b679e1916a4a)
i didn't change anything

**Comment by VOREGA** [comment]
It was working fine 1 hour ago

**Comment by Mid0aria** [comment]
![image](https://github.com/Mid0aria/owofarmbot/assets/45801669/9221b77d-b76a-4891-b3ca-4992959100a5)

**Comment by Mid0aria** [comment]
evladım aptalmısın baksana pinlerde duruyor

**Comment by VOREGA** [comment]
This has nothing to do with the pinned issue.

**Comment by Mid0aria** [comment]
kanaldan contenti çekemiyor yani pindekiyle aynı hata anladın az ingilizcen olsa zaten anlardın hatayı

**Comment by VOREGA** [comment]
![313131](https://github.com/Mid0aria/owofarmbot/assets/72041595/8d77efea-99d0-4832-a816-5b9e08bc1a9b)

**Comment by VOREGA** [comment]
owoyu yemişler
