### ISSUE TITLE
keep getting this error right after bot starts

### ISSUE THREAD

**Issue by pinbone** [Mid0aria/owofarmbot#31]
C:\Users\PC\Downloads\owofarmbot-main\bot.js:1798
                        cont[0].description.includes(
                                ^

TypeError: Cannot read properties of undefined (reading 'description')
    at Request._callback (C:\Users\PC\Downloads\owofarmbot-main\bot.js:1798:33)

Node.js v18.15.0

**Comment by Mid0aria** [comment]
https://github.com/Mid0aria/owofarmbot/issues/11

**Comment by Wakasumi1** [comment]
any help i take this error too
