### ISSUE TITLE
dont know how to use can anyone explain me in detail

### ISSUE THREAD

**Issue by Kinh05018410298** [Mid0aria/owofarmbot#32]

**Comment by VihaanReddyM** [comment]
did you install the code

**Comment by Kinh05018410298** [comment]
Yay but I can't see the confing.json file I checked all there is no such file

**Comment by VihaanReddyM** [comment]
open the folder

**Comment by Kinh05018410298** [comment]
I did

**Comment by VihaanReddyM** [comment]
OK now

**Comment by Kinh05018410298** [comment]
Bro i am not getting any .json files

**Comment by Kinh05018410298** [comment]
![Screenshot (32)](https://github.com/Mid0aria/owofarmbot/assets/138672701/9c20e817-2e0b-4736-84e7-782b875a4960)

**Comment by VihaanReddyM** [comment]
enter the channel id
and other info and the channels should be different ok

**Comment by Kinh05018410298** [comment]
Yay I entered next what should I do?

**Comment by VihaanReddyM** [comment]
not open the terminal and type cd <location of the folder>
then you can type 
"""
npm i
"""
then
"""
node bot.js
"""

it should run

**Comment by Kinh05018410298** [comment]
https://github.com/Mid0aria/owofarmbot/assets/138672701/12aed671-7fa5-4653-a7ac-4acf28d50f69

bro see this video

**Comment by Mid0aria** [comment]
https://nodejs.org/dist/v20.4.0/node-v20.4.0-x64.msi

**Comment by Kinh05018410298** [comment]
It started working but only sendibg 2 messages Owo Lvl And Owo Daily That Also Only 1 Time

**Comment by VihaanReddyM** [comment]
run it again and send the pic then only we can tell what happened

**Comment by Kinh05018410298** [comment]
https://github.com/Mid0aria/owofarmbot/assets/138672701/99ce2e5a-1ac7-4e3d-a533-c4045c1b0e83

bro what is this new problem i entered everything correct only i checked twice
