### ISSUE TITLE
Sacrifice is not functioning 

### ISSUE THREAD

**Issue by VihaanReddyM** [Mid0aria/owofarmbot#36]
the sac function is sacing all the animals

**Comment by Mid0aria** [comment]
![image](https://github.com/Mid0aria/owofarmbot/assets/45801669/f9623319-bf5c-47b2-a4c6-66921383ec78)
you added this in the code, idiot

**Comment by VihaanReddyM** [comment]
sorry lol

**Comment by VihaanReddyM** [comment]
i only started learning code like few months ago soooo sorry

**Comment by 420002** [comment]
did this get fixed?
