### ISSUE TITLE
support for mobile using replit? 

### ISSUE THREAD

**Issue by Kayows12** [Mid0aria/owofarmbot#38]

**Comment by VihaanReddyM** [comment]
did you try using it in replit

**Comment by Kayows12** [comment]
> 

yes i did but it doesn't work, it says it requires desktop

**Comment by VihaanReddyM** [comment]
you can make a fork of the repo and remove the lines 2 to 6 it should work pls try it

**Comment by Kayows12** [comment]
> you can make a fork of the repo and remove the lines 2 to 6 it should work pls try it

oh what lines?

**Comment by VihaanReddyM** [comment]
lines 2 to 6

**Comment by VihaanReddyM** [comment]
sorry lines 3 to 6

this pice of code

```
if (os.type() !== "Windows_NT") {
    console.log("Only Windows !!!");
    process.exit(0);
}
```

**Comment by VihaanReddyM** [comment]
https://replit.com/join/ayixofybkj-nerverstop



join this replit, i have made the required changed

**Comment by Kayows12** [comment]
> https://replit.com/join/ayixofybkj-nerverstop
> 
> join this replit, i have made the required changed

Sorry for late reply but thanks, I'll try it :)

**Comment by Kayows12** [comment]
i tried and it worked although the dm captcha solve isn't working i think
