### ISSUE TITLE
my cmd crashes whenever i use the command node.js

### ISSUE THREAD

**Issue by Ducanhtomau1** [Mid0aria/owofarmbot#40]
i cant open the file with node directly
like when i choose to open the file with node.js it just turns the app off

**Comment by Ducanhtomau1** [comment]
![F620B3D2-D714-42AD-B9B8-8AC5D2D139D3](https://github.com/Mid0aria/owofarmbot/assets/141422094/393cb4c2-92e9-43e6-8253-09ee499bb5df)

**Comment by Mid0aria** [comment]
![image](https://github.com/Mid0aria/owofarmbot/assets/45801669/200942ec-9fc7-49f7-9685-a3b590b750ae)

type this
