### ISSUE TITLE
anti captcha not working

### ISSUE THREAD

**Issue by ringaroundtherosy** [Mid0aria/owofarmbot#43]
got a captcha in chat, didnt send a dm but got a captcha in chat and my alt got banned for an hour. don't know if it has something to do with the fact im only using auto hunt and ban but it didnt stop.

**Comment by ringaroundtherosy** [comment]
update: the owo bot captcha system was changed entirely. pretty sure the devs already know this but yeah

**Comment by Mid0aria** [comment]
I don't know, when I use it myself, it stops the bot and sends a notification when there is a captcha.

**Comment by ringaroundtherosy** [comment]
it doesn't send a dm. there's like a new captcha type thing. you have to go onto the site and verify

**Comment by VihaanReddyM** [comment]
yea

**Comment by Mid0aria** [comment]
The captcha grant time of the owo bot has been extended https://github.com/Mid0aria/owofarmbot/commit/c6aa811e9ae9a30bf39c7ec6528f1ce039fd1939

**Comment by VihaanReddyM** [comment]
bro captcha is not working
i got banned to pls check
