### ISSUE TITLE
error of undefined properties.

### ISSUE THREAD

**Issue by milkyyyyyyyyyyyyyy** [Mid0aria/owofarmbot#47]
Hello mister / miss, I hope your doing well. I've been using your script this past few days, and honnestly it's incredible, thank you for that !  But tonight when I put it back on, it tells me that a TypeError come on now. While I've not touch any of the other fills than config one.
Imma put the messages here but, know that I already did all the process twice, but it still the same message so, maybe you can solve it ? Thank you again for this, and hope you respond me soon, byee. 

TypeError: Cannot read properties of undefined (reading 'description')                                                      at Request._callback (C:\Users\super\Documents\owofarmbot-main\bot.js:937:43)                                           at self.callback (C:\Users\super\Documents\owofarmbot-main\node_modules\request\request.js:185:22)                      at Request.emit (node:events:514:28)                                                                                    at Request.<anonymous> (C:\Users\super\Documents\owofarmbot-main\node_modules\request\request.js:1154:10)               at Request.emit (node:events:514:28)                                                                                    at IncomingMessage.<anonymous> (C:\Users\super\Documents\owofarmbot-main\node_modules\request\request.js:1076:12)       at Object.onceWrapper (node:events:628:28)                                                                              at IncomingMessage.emit (node:events:526:35)                                                                            at endReadableNT (node:internal/streams/readable:1376:12)                                                               at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by milkyyyyyyyyyyyyyy** [comment]
I do have the code in front of me, and yes I don't see that the line 937 var des = cont[0].description;     that .description is not on lighty, while others properties are in different colors, hit me up when you got times.

**Comment by Mid0aria** [comment]
https://github.com/Mid0aria/owofarmbot/issues/11
