### ISSUE TITLE
getting error 

### ISSUE THREAD

**Issue by Ankit-0777** [Mid0aria/owofarmbot#50]
D:\ankit\owofarmbot-main\owofarmbot-main\bot.js:1928
                        cont[0].description.includes(
                                ^

TypeError: Cannot read properties of undefined (reading 'description')
    at Request._callback (D:\ankit\owofarmbot-main\owofarmbot-main\bot.js:1928:33)

Node.js v20.5.1

**Comment by Mid0aria** [comment]
FIXED https://github.com/Mid0aria/owofarmbot/commit/c6aa811e9ae9a30bf39c7ec6528f1ce039fd1939
