### ISSUE TITLE
BanByPass not working

### ISSUE THREAD

**Issue by Ankit-0777** [Mid0aria/owofarmbot#54]
i got banned from owo for 1 day because when the captcha was coming in the chat then also bot was not stopping and farming and i got banned because of that please fix it as soon as possible

**Comment by VihaanReddyM** [comment]
send the screen shot

**Comment by Mid0aria** [comment]
If owo is running slow or your internet is slow, the farm bot will not work synchronously and as a result, timings and special functions cannot fulfill their duties, so there will be situations such as bans.
Long story short, the problem is with you, not the farm bot.
