### ISSUE TITLE
cannot restart

### ISSUE THREAD

**Issue by toolaruh** [Mid0aria/owofarmbot#57]
PS C:\Users\Admin\Desktop\owofarmbot-main> npm install

up to date, audited 99 packages in 1s

7 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
PS C:\Users\Admin\Desktop\owofarmbot-main>

**Comment by toolaruh** [comment]
PS C:\Users\Admin\Desktop\owofarmbot-main> npm audit
# npm audit report

request  *
Severity: moderate
Server-Side Request Forgery in Request - https://github.com/advisories/GHSA-p8p7-x288-28g6
Depends on vulnerable versions of tough-cookie
No fix available
node_modules/request

tough-cookie  <4.1.3
Severity: moderate
tough-cookie Prototype Pollution vulnerability - https://github.com/advisories/GHSA-72xf-g2v4-qvf3
No fix available
node_modules/tough-cookie

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.
PS C:\Users\Admin\Desktop\owofarmbot-main>

**Comment by toolaruh** [comment]
7 packages are looking for funding
  run `npm fund` for details
PS C:\Users\Admin\Desktop\owofarmbot-main> npm fund
owofarmbot@0.0.0
+-- https://github.com/chalk/chalk?sponsor=1
| | `-- chalk@4.1.2
| `-- https://github.com/chalk/ansi-styles?sponsor=1
|     `-- ansi-styles@4.3.0
+-- https://github.com/sponsors/sindresorhus
|   `-- delay@5.0.0, is-docker@2.2.1
+-- https://github.com/sponsors/RubenVerborgh
|   `-- follow-redirects@1.15.2
+-- https://github.com/sponsors/feross
|   `-- safe-buffer@5.2.1
`-- https://github.com/sponsors/epoberezkin
    `-- ajv@6.12.6

PS C:\Users\Admin\Desktop\owofarmbot-main>

**Comment by toolaruh** [comment]
never mind it works again. Thank you for the code

**Comment by VihaanReddyM** [comment]
then close the issue!!!
