### ISSUE TITLE
When I run it there is an error like this (replit mobile}

### ISSUE THREAD

**Issue by Zenuci** [Mid0aria/owofarmbot#59]
![Screenshot_2023-09-17-08-42-10-95](https://github.com/Mid0aria/owofarmbot/assets/127984783/65e6f0fc-2cf9-4624-841f-e58b713de309)

**Comment by Zenuci** [comment]
@Mid0aria can you help me?

**Comment by Mid0aria** [comment]
Can you create a new repl and try?

**Comment by Mid0aria** [comment]
try npm run run

**Comment by Mid0aria** [comment]
![Screenshot_20230918_144230_GitHub.jpg](https://github.com/Mid0aria/owofarmbot/assets/45801669/498daf9d-81c5-46d5-80a2-b44bae644299)
