### ISSUE TITLE
There is a error when i try to run it pls help

### ISSUE THREAD

**Issue by VihaanReddyM** [Mid0aria/owofarmbot#6]
then I ran the program it gave me this probelm:

D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\bot.js:1692
                        cont[0].description.includes(
                                ^

TypeError: Cannot read properties of undefined (reading 'description')
    at Request._callback (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\bot.js:1692:33)

Node.js v20.1.0

Vs code shows it has almost 200 issues pls help

**Comment by Vihaan123456123** [comment]
it works all fine if i turn off autoquest

**Comment by Mid0aria** [comment]
most likely you are using the same channel id please use different channel for each token

**Comment by Vihaan123456123** [comment]
i am still getting this error

D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\bot.js:381
                            check(extratoken, extrachannelid, "Extra Token");
                            ^

ReferenceError: check is not defined
    at Timeout._onTimeout (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\bot.js:381:29)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

Node.js v20.1.0

**Comment by Mid0aria** [comment]
i fixed this error two days ago update the bot

**Comment by Vihaan123456123** [comment]
it is showing me this error now

node:internal/modules/cjs/loader:1085
  throw err;
  ^

Error: Cannot find module 'D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Module._load (node:internal/modules/cjs/loader:928:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.1.0what does it mean pls help

**Comment by Mid0aria** [comment]
you are trying to node the wrong file, open cmd in the bot folder and type node bot.js

**Comment by Vihaan123456123** [comment]
now if i try to use autoquest i get this error. sorry if i am troubling you.

D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\bot.js:1692
                        cont[0].description.includes(
                                ^

TypeError: Cannot read properties of undefined (reading 'description')
    at Request._callback (D:\coding\python\discord-selfbot-owo-bot-main\owofarmbot-main\owofarmbot-main\bot.js:1692:33)

Node.js v20.1.0

**Comment by Vihaan123456123** [comment]
the updater is prbably not working as when i update almost all the files like bot.js and the rest are showing 404:not found
