### ISSUE TITLE
> @Mid0aria can you help me?

### ISSUE THREAD

**Issue by Zenuci** [Mid0aria/owofarmbot#61]
> @Mid0aria can you help me?

bro you need to remove start just npm run

_Originally posted by @Hieiisbw1 in https://github.com/Mid0aria/owofarmbot/issues/59#issuecomment-1723115535_

**Comment by Zenuci** [comment]
![Uploading Screenshot_2023-09-18-22-31-25-52.png…]()

**Comment by Zenuci** [comment]
![Screenshot_2023-09-18-22-29-51-08](https://github.com/Mid0aria/owofarmbot/assets/127984783/36264977-ad6e-4248-b2bf-831a104b3d93)

**Comment by Zenuci** [comment]
![Uploading Screenshot_2023-09-18-22-31-25-52.png…]()

**Comment by Zenuci** [comment]
![Uploading Screenshot_2023-09-18-22-31-25-52.png…]()

**Comment by Mid0aria** [comment]
type npm i

**Comment by Zenuci** [comment]
![Uploading Screenshot_2023-09-18-22-37-41-54.png…]()

**Comment by Zenuci** [comment]
That

**Comment by Mid0aria** [comment]
![image](https://github.com/Mid0aria/owofarmbot/assets/45801669/17af52e5-9f12-4b61-8cf6-3c86c2998c8f)

**Comment by Zenuci** [comment]
@Mid0aria Like at the beginning 
![Uploading Screenshot_2023-09-17-08-42-10-95.png…]()

**Comment by Zenuci** [comment]
![Screenshot_2023-09-17-08-42-10-95](https://github.com/Mid0aria/owofarmbot/assets/127984783/1c76ec88-ffbd-4a56-a019-4de4b4e07444)

**Comment by Zenuci** [comment]
![Screenshot_2023-09-19-01-07-34-01](https://github.com/Mid0aria/owofarmbot/assets/127984783/2acae5b5-4f26-40eb-987f-bf21584b7638)

**Comment by CallMeZunggHieu** [comment]
> ![Screenshot_2023-09-19-01-07-34-01](https://user-images.githubusercontent.com/127984783/268735626-2acae5b5-4f26-40eb-987f-bf21584b7638.png)

Type npm install chalk@4.1.2

After it type Npm run

And type Node bot.js

**Comment by Zenuci** [comment]
![Screenshot_2023-09-19-18-15-52-81](https://github.com/Mid0aria/owofarmbot/assets/127984783/fbc80448-6353-4294-bc89-7408edd9dc54)

**Comment by Zenuci** [comment]
When I installed chalk it appeared

**Comment by CallMeZunggHieu** [comment]
> When I installed chalk it appeared

Am think bro need to download replit :0

**Comment by Zenuci** [comment]
> > When I installed chalk it appeared
> 
> Am think bro need to download replit :0

I've used it but it still doesn't work

**Comment by Zenuci** [comment]
Why don't you use a replit fork?

> > ![Screenshot_2023-09-19-01-07-34-01](https://user-images.githubusercontent.com/127984783/268735626-2acae5b5-4f26-40eb-987f-bf21584b7638.png)
> 
> Type npm install chalk@4.1.2
> 
> After it type Npm run
> 
> And type Node bot.js

**Comment by Mid0aria** [comment]
3 days of inactivity
