### ISSUE TITLE
Now there is an Error called " syntaxerror: "undefined" is not valid json "

### ISSUE THREAD

**Issue by Zymro-dev** [Mid0aria/owofarmbot#63]
I dont know what to do but plz fix this.

**Comment by Mid0aria** [comment]
please add console output

**Comment by Zymro-dev** [comment]
Umm What do u mean by that ????

**Comment by VihaanReddyM** [comment]
send a picture of the entire error that you are receiving

**Comment by Mid0aria** [comment]
Reason for closure: Inactivity

**Comment by spdjky** [comment]
I ran the bot few times. After like 3 4 times it was unable to get checklist and the bot functioned.
