### ISSUE TITLE
Main Token Channel ID

### ISSUE THREAD

**Issue by peng1285** [Mid0aria/owofarmbot#68]
![image](https://github.com/Mid0aria/owofarmbot/assets/105729482/e4eec7ca-7e9b-4687-bba7-9ecf7e5045cd)
why?

**Comment by Mid0aria** [comment]
https://youtu.be/sso05qx8Hac

**Comment by peng1285** [comment]
> https://youtu.be/sso05qx8Hac

thank you when i'm put my token i forget to save it -,- haha
