### ISSUE TITLE
can you add coinflip like this?

### ISSUE THREAD

**Issue by peng1285** [Mid0aria/owofarmbot#69]
can you add auto gamble coinflip like this
if i flip 10000 and win it will repeat and
if i lose it will Continue to flip 40000 if i win bot will go back to flip 10000
if i lose it will continue to flip 90000 if i win bot will go back to flip 10000
if i lose it will continue to flip 150000 and go back to flip 10000

and amount we can change

sorry my english so bad-,-

**Comment by peng1285** [comment]
@VihaanReddyM

**Comment by VihaanReddyM** [comment]
ok wait i will try, but will take time

**Comment by thevzz** [comment]
just do x2 if bet is lost its more efficient
like always bet with idk "startbet" : value
and lets say value is 1000
if won go with 1000 again 
if lost x2 value = bet with 2000
if lost again x2 second value = bet with 4000
and more.. but if won go back to startbet 1000

**Comment by thevzz** [comment]
> follow the progress here and @Mid0aria pls help
> 
> https://github.com/VihaanReddyM/owofarmbot

thanks for your work brother

**Comment by VihaanReddyM** [comment]
it is still a work in progress....

**Comment by peng1285** [comment]
> just do x2 if bet is lost its more efficient like always bet with idk "startbet" : value and lets say value is 1000 if won go with 1000 again if lost x2 value = bet with 2000 if lost again x2 second value = bet with 4000 and more.. but if won go back to startbet 1000

make it can change amount step by step it good

**Comment by peng1285** [comment]
> it is still a work in progress....

Thank you very much for your work

**Comment by peng1285** [comment]
> it is still a work in progress....

and one more do it on slot too

**Comment by VihaanReddyM** [comment]
i feel like slot is a waste of money but i will try the coinflip is done and i will open a PR for that and mark it as a draft first

**Comment by thevzz** [comment]
> i feel like slot is a waste of money but i will try the coinflip is done and i will open a PR for that and mark it as a draft first

yeah slot is waste of money because its not 50/50 like coinflip thx brother

**Comment by thevzz** [comment]
@VihaanReddyM idk why but coinflip is always default amount even after lost bet

**Comment by VihaanReddyM** [comment]
checking........

**Comment by VihaanReddyM** [comment]
Can you send me a picture because it seems to be working right on my pc

**Comment by VihaanReddyM** [comment]
![image](https://github.com/Mid0aria/owofarmbot/assets/87236325/d930d6d9-24c6-4eff-8978-fdf871f1f61f)

**Comment by thevzz** [comment]
> ![image](https://user-images.githubusercontent.com/87236325/275764828-d930d6d9-24c6-4eff-8978-fdf871f1f61f.png)

![image](https://github.com/Mid0aria/owofarmbot/assets/147729241/88366f6b-00ef-4524-8995-ceef162da409)
sometimes it reads that i won but i didnt won + its going from 10 to 30 but when i lose more its not going to 90 for example

**Comment by thevzz** [comment]
![image](https://github.com/Mid0aria/owofarmbot/assets/147729241/674e1e64-87cd-4da4-80a4-4b54c908613c)
@VihaanReddyM

**Comment by peng1285** [comment]
> ![image](https://user-images.githubusercontent.com/87236325/275764828-d930d6d9-24c6-4eff-8978-fdf871f1f61f.png)

can you put function like we can change next flip money x2 or x3 it good cuz it will safe if we play from 10000

**Comment by VihaanReddyM** [comment]
ok i will try

**Comment by peng1285** [comment]
> ok i will try

![image](https://github.com/Mid0aria/owofarmbot/assets/105729482/9e7855b2-f3ce-48e2-89bc-b1473cbce2ee)
![image](https://github.com/Mid0aria/owofarmbot/assets/105729482/98b90f7b-7e92-4559-bd3e-708a3c887dd6)
it error when internet slow and flip cooldown

**Comment by thevzz** [comment]
> > ok i will try
> > ![image](https://github.com/Mid0aria/owofarmbot/assets/105729482/50680aa8-107f-41b2-9f9d-c4ea0b8529ed)
> 
> ![image](https://user-images.githubusercontent.com/105729482/275834800-98b90f7b-7e92-4559-bd3e-708a3c887dd6.png) it error when internet slow and flip cooldown

![image](https://github.com/Mid0aria/owofarmbot/assets/147729241/a5ae3dd9-8254-4d8c-8957-1f67ec1da5f0)
i know its not the best internet but still dont think connection fails here

**Comment by VihaanReddyM** [comment]
ok working on it

**Comment by VihaanReddyM** [comment]
pls check it now

**Comment by VihaanReddyM** [comment]
@peng1285 @thevzz is it working or any bugs
pls tell fast

**Comment by VihaanReddyM** [comment]
@Mid0aria you can close this issue now
