### ISSUE TITLE
undefined is not a valid JSON

### ISSUE THREAD

**Issue by spdjky** [Mid0aria/owofarmbot#72]
Sometimes the bot gets a checklist error and functions normally.
But if the bot fetches the checklist successfully it gives this error.
![Screenshot 2023-11-05 195551](https://github.com/Mid0aria/owofarmbot/assets/113653139/166f64dc-6000-4c36-9733-14e149eeeaad)

**Comment by VihaanReddyM** [comment]
Yea it happens to me also

**Comment by VihaanReddyM** [comment]
i honestly dont know, try to use the token from the config.json
