### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by 3gconan2k8** [Mid0aria/owofarmbot#80]
![image](https://github.com/Mid0aria/owofarmbot/assets/152409776/3ff6cc14-abc4-49eb-8c51-004101e88023)
why my bot no work although i was add token but it  said i lost my token

**Comment by Mid0aria** [comment]
It doesn't say that your token is wrong, it says that the channel ID you entered into your token is wrong, you really can't be that stupid.

**Comment by Mid0aria** [comment]
and delete the image, your token appears
