### ISSUE TITLE
Main Token / 401: Unauthorized (TOKEN WRONG!)

### ISSUE THREAD

**Issue by Jivesh-Bisht** [Mid0aria/owofarmbot#81]
It says the token is wrong but the the token is correct I used another application that uses the same token and it works like a charm only in this code it doesn't work? Is it due to any new updates from discord blocking these type of applications or is it just me? Any other ways to get the token other than going to network tab and then sending a message and then checking for the authorization header for the token?

**Comment by Mid0aria** [comment]
You may have renewed your discord token or you may have left a space when writing the token in the config file.
