### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by morchaavx** [Mid0aria/owofarmbot#82]
![IMG_20231231_124906](https://github.com/Mid0aria/owofarmbot/assets/154520640/22a23190-27c2-4b80-a724-1fcfb2c64aeb)

**Comment by Mid0aria** [comment]
Accept the owo bot's agreement and restart the bot

**Comment by morchaavx** [comment]
> Accept the owo bot's agreement and restart the bot

how sir :)

**Comment by Mid0aria** [comment]
Type owo hunt into the owo bot and wait for a while, click accept from the buttons that will show you the contract and that's it.

**Comment by morchaavx** [comment]
> Type owo hunt into the owo bot and wait for a while, click accept from the buttons that will show you the contract and that's it.

Terms of service before playing owo?, I have accepted it before

**Comment by Mid0aria** [comment]
Open another server, set the channels and run the bot there. If it still fails, delete the bot and reinstall it (this includes nodejs)

**Comment by morchaavx** [comment]
> Open another server, set the channels and run the bot there. If it still fails, delete the bot and reinstall it (this includes nodejs)

still same:(

**Comment by Mid0aria** [comment]
Could you try setting the enable variable of the times indicator in the config.json file to false?
![image](https://github.com/Mid0aria/owofarmbot/assets/45801669/caae79ac-91ef-4764-9895-0cbf348c1ea4)

**Comment by morchaavx** [comment]
> Could you try setting the enable variable of the times indicator in the config.json file to false? ![image](https://private-user-images.githubusercontent.com/45801669/293495212-caae79ac-91ef-4764-9895-0cbf348c1ea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMDg5MjUsIm5iZiI6MTcwNDAwODYyNSwicGF0aCI6Ii80NTgwMTY2OS8yOTM0OTUyMTItY2FhZTc5YWMtOTFlZi00NzY0LTk4OTUtMGNiZjM0OGMxZWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA3NDM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNTJlM2MzZTViNDg0ZWZmMDViYTIzYjIxMTJkY2RjOWE1MTZiZDE3ZDVmODdmNDZkZDFmZjdkYTQ2MGEzNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jx_jOFDLHdzN85J8fIm7C2J1DAGgXxY7z4yvVvVap4w)

I've done it sir

**Comment by Mid0aria** [comment]
Does it still give the error?

**Comment by morchaavx** [comment]
> Does it still give the error?

yes still sir

**Comment by Mid0aria** [comment]
1- Download f droid and download termux from f droid
2- Open termux and grant necessary permissions (file access etc.)
3- Type the following into the command line in Termux:

pkg install nodejs
pkg install nodejs-lts
pkg install yarn
pkg install git
git clone https://github.com/Mid0aria/owofarmbot.git
cd owofarmbot
npm install

With these commands, you can install the bot on your phone via Termux.

4- To edit the config file, type "nano config.json" and change where you need to change (token, channels, etc.).

5- to run the latest bot Type "node bot.js" and see if it gives an error. If it still gives an error, there is nothing we can do.

**Comment by Mid0aria** [comment]
* You must enter your token in the .env file without any spaces.

**Comment by morchaavx** [comment]
> 1- Download f droid and download termux from f droid 2- Open termux and grant necessary permissions (file access etc.) 3- Type the following into the command line in Termux:
> 
> pkg install nodejs pkg install nodejs-lts pkg install yarn pkg install git git clone https://github.com/Mid0aria/owofarmbot.git cd owofarmbot npm install
> 
> With these commands, you can install the bot on your phone via Termux.
> 
> 4- To edit the config file, type "nano config.json" and change where you need to change (token, channels, etc.).
> 
> 5- to run the latest bot Type "node bot.js" and see if it gives an error. If it still gives an error, there is nothing we can do.

work sir yeaaah

**Comment by morchaavx** [comment]
how to stop in termux?

**Comment by Mid0aria** [comment]
ctrl + z
