### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by morchaavx** [Mid0aria/owofarmbot#83]
![IMG_20231231_161629](https://github.com/Mid0aria/owofarmbot/assets/154520640/d8ed2957-ced9-46e1-a594-3bb49e4d2296)

**Comment by Mid0aria** [comment]
termux-setup-storage
npm install

**Comment by morchaavx** [comment]
> termux-setup-storage npm install

still same

**Comment by yvreK** [comment]
Go to apps > find app info > click app permissions then enable everything in there. After that do the command he gave u.
termux-setup-storage 
npm install
