### ISSUE TITLE
This randomly shows up after a couple of minutes, any solution to it?

### ISSUE THREAD

**Issue by yvreK** [Mid0aria/owofarmbot#86]
![Screenshot_2024-01-01-07-50-00-663_com termux-edit](https://github.com/Mid0aria/owofarmbot/assets/78933419/46bfa6bf-9b07-4422-b912-34896774fd47)

ANOTHER ERROR.

![Screenshot_2024-01-02-02-16-33-02.jpg](https://github.com/Mid0aria/owofarmbot/assets/78933419/38724ade-5dab-4545-9669-45d529fa19f5)

**Comment by Mid0aria** [comment]
check your channel ids
