### ISSUE TITLE
Multiple feature requests

### ISSUE THREAD

**Issue by sneazy-ibo** [Mid0aria/owofarmbot#88]
### Variation time
Instead of only being able to send the commands in a specific time frame which is the exactly same, being able to choose a base value and a variation value to add up to a random cooldown. The bot gets almost every 5min detected in my case using a base value in milliseconds and also an customizable variation value also in milliseconds would make it way harder to detect since the intervals of sent messages will always be random in an interval you choose.
### Gem selection
It would be nice if we can select which gems the bot is allowed to use since it's not smart enough to see the profit by high quality gems used in the same time and will just use whatever is the highest atm.
### Typing indicator
Showing an typing indicator between the command cooldowns would make the selfbot way harder to detect for server members.
### Message alarm
Giving an warning of a message is sent in an channel which did not come from your accounts or OwO bot would be a great way to not get caught using an macro.

### Bugs
- the rich presence can't be turned off
- dnd is not enabled and the bot fails to send captchas sometimes (I will find out what triggers this sooner or later)

Please rewrite the config file, it's so chaotic right now and there are also some commands toggled multiple times although they are the same

**Comment by sneazy-ibo** [comment]
### Macro access through discord
Add an Option to start and end the macro through discord directly by sending custom messages like "owost" or wtv, having them look like owocommands will rise less suspicion, smth like "owohelp inv" is already a perfect trigger. There is also another benefit for doing this which is easy access for people who hosted the macro, instead of exiting the bot, stopping all the commands and listening to the triggers is how it can work.
### Random Gamble Cooldowns
Add a minimum and maximum cooldown for gambling too, having those enabled still triggers the macro detection pretty easily since they are still sent in the exact same time.

Finally fix the rich presence damn, I always have to disable the activity status toggle through discord or play around in the bot.js file myself to get it disabled.

**Comment by Mid0aria** [comment]
discord rpc fixed && typing indicator added

**Comment by sneazy-ibo** [comment]
Well done :)

**Comment by aiueotio** [comment]
how to set gamble coin flip, if lose bet x2 and if win back to default i set the bet?
