### ISSUE TITLE
Token Error

### ISSUE THREAD

**Issue by sneazy-ibo** [Mid0aria/owofarmbot#95]
After updating to the latest version the bot doesn't start anymore, all my inputs are right and I haven't changed anything since the last commit in the config settings but it still gives me this error:
```
Captcha Bypass
Main Token / 401: Unauthorized (TOKEN WRONG!)
Updater Repo Version: 0.0.3 / Updater Installed Version: 0.0.3
Repo Version: 1.0.6.2 / Installed Version: 1.0.6.2
```
There must have been a new error in the code after the latest commit causing this. I am 100% sure that all my date I provided in the config file is correct and even installed the repo again on my device

**Comment by Mid0aria** [comment]
fixed
